import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { BaseProvider } from "@/src/provider/base-provider";
import { L10nProvider } from "@/src/provider/l10n-provider";
import { getDictionary, hasLocale } from "@/src/dictionaries/dictionaries";
import { notFound } from "next/navigation";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: "en" | "tr" }>;
}>) {
  const { lang } = await params;

  if (!hasLocale(lang)) notFound();
  const dict = await getDictionary(lang);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {
          <BaseProvider>
            <L10nProvider lang={lang} dictionary={dict}>
              {children}
              <Toaster />
            </L10nProvider>
          </BaseProvider>
        }
      </body>
    </html>
  );
}
